title: Afshin Arab # your name (or website title) here
logo: "/images/Logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  data analyst | coder. inspired by tough problems. 
  <br><br>
  I give insight to the data and help make data-driven decisions. 
  <br><br>
  <a href="https://www.linkedin.com/in/afshin-arab">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
